### ISSUE TITLE
actions-document-open-read-only

### ISSUE THREAD

**Issue by NeoBlack** [TYPO3/TYPO3.Icons#117]
In my opinion, the white space around the overlay is not "clear" it looks not symmetric!?

<img width="502" alt="wmdbsystems_t3_icons" src="https://cloud.githubusercontent.com/assets/1128085/10494182/23908bf2-72b5-11e5-83e6-81e180987a2f.png">

**Comment by raphaelokon** [comment]
@NeoBlack Agree.
Is anyone working on this one? If not, I'd pick it and clean up the whitespace around the lock overlay.

**Comment by NeoBlack** [comment]
much better, thank you!

**Comment by raphaelokon** [comment]
Cheers @NeoBlack  :)
