### ISSUE TITLE
Sort general feedback for v0.0.4 icons

### ISSUE THREAD

**Issue by raphaelokon** [TYPO3/TYPO3.Icons#221]
Categories and prioritise the following issues:
- [x] Bei manchen Overlays der Action-Icons habt ihr einen "Schein" außen ums Overlay, der größer ist als bei anderen. Groß ist "actions-document-open-read-only" und damit auch besser erkennbar und "actions-document-save-translation" ist klein und damit schlechter erkennbar. Oder auch "actions-document-save-new"
- [x] "actions-document-save-view" warum gibt es hier noch das Auge und nicht den Bildschirm, wie bei "actions-preview"?
- [x] "actions-filter" würde ich unten dünner machen und eine Trennlinie zwischen oberem und unterem Teil einsetzen. 
- [x] ~~"actions-logout" würde ich nicht als Ein-/Aus-Schalter machen, man schaltet TYPO3 ja nicht aus. logout icon.~~
- [x] ~~"actions-page-move" kann man kaum von einem Plus unterscheiden. Etwas dünnere Linien vielleicht beim Pfeil-Kreuz.~~
- [x] "actions-system-pagemodule-open" hat noch die Lupe. Vorgänger des Auges, oder?
- [ ] "actions-system-shortcut-active" sieht fett aus. Schau mal, schnell einen gemacht, der gerade ist:  (rechts ist eurer)
- [x] "actions-version-workspace-sendtostage" ist auf dunklem Button schwarz.
- [x] "actions-view" wieder das Auge.
- [x] Bei der "Apps"-Icons hast du das im Büro besprochene Problem, dass man die Overlays sehr schlecht erkennen kann. Ich kenne den Einsatzort nicht. Und manche haben auch eine schwarze Outline ums Overlay. Bsp. "apps-pagetree-page-backend-users".
- [x] "content-plugin" sehr schwer zu erkennen. Entweder die den Baustein markanter, also die "Nippel" oben irgendwie trennen oder hervorheben oder ein anderes Icons. Puzzleteil oder besser noch der 3d-Würfel aus den Action-Icons.
- [ ] "mimetypes-excel" würde ich das X dünner machen. Siehe aktuelles Icon von M$
- [ ] "mimetypes-media-audio" sieht plump aus. Bisschen nettere Note würde nicht schaden.
- [ ] "mimetypes-powerpoint" ebenfalls dünneres P und den Punkt weg
- [ ] "mimetypes-text-js" dünnere Schrift
- [ ] "mimetypes-text-php" warum nicht hier auch das Logo?
- [ ] "mimetypes-word" dünneres W
- [ ] "mimetypes-x-content-plugin" s. o.
- [x] "mimetypes-x-content-script" was ist das?
- [ ] "mimetypes-x-tx_rtehtmlarea_acronym" diese Schrift sieht einfach komisch aus. Condensed, zu dick, ich weiß es nicht, aber sehr strange
- [ ] "mimetypes-x-tx_scheduler_task_group" find ich sehr super!
- [x] "module-about" 
- [x] Das Buch, wie auch bei den anderen Buch-Icons passt nicht zum Rest. Ich glaube, da es so stark schräg steht. Warum nicht das selbe Buch wie bei den Action-Icons?
- [x] "module-belog" wirkt eher wie etwas im Zusammenhang mit Copy&Paste. Evtl. nur ein Icon und ein Overlay "LOG"
- [x] "module-extensionmanager" s. o. 3D-Würfel find ich am besten, aber jetzt kommt neben dem Baustein auch noch ein Puzzle-Teil hinzu. Ich würde überall das Selbe nehmen
- [x] "module-filelist" warum ne Wolke? Weil man auch Mounts in der Cloud haben kann?
- [x] "module-help" noch nich fertig?
- [x] "module-indexed_search" fehlt der Bezug zur Suche
- [x] "module-page" ist das Icon als auch der Name nicht quatsch? Sollte man das modul "Page" nicht besser "Layout" nennen und dann auch hier das Icon vom Backend-Layout verwenden?
- [x] "module-viewpage" auch hier würde ich das Icon entfernen und ein Icon aus diversen Geräten bauen. Monitor, Tablet, Smartphone oder so. Das kann das Modul doch emulieren, oder?
- [x] "module-workspaces" cool, aber oben gab es ein anderes Icon zu Workspaces. Würde diese hier überall verwenden
- [x] Overlays hatten wir ja schon besprochen

**Comment by benjaminkott** [comment]
obsolete
