### ISSUE TITLE
open document formats (LibreOffice/OpenOffice.org)

### ISSUE THREAD

**Issue by erredeco** [TYPO3/TYPO3.Icons#268]
this ticket: https://forge.typo3.org/issues/27475 asked for the creation of icons to manage openoffice documents:

.odt (text)
.ods (spreadsheet)
.odp (presentation)
.odg (drawing)
.odf (database)

I don't know if it is necessary to create separate icons or to manage these files via existing icons:

.odt (text)    > mimetypes-word
.ods (spreadsheet)  > mimetypes-excel
.odp (presentation) > mimetypes-powerpoint
.odg (drawing)   > mimetypes-media-image (?)  
.odf (database) >  mimetypes-application (?)

**Comment by benjaminkott** [comment]
All icons are available and added to 0.0.9
Core Patch pending: https://review.typo3.org/#/c/45187/
