### ISSUE TITLE
Better differentiate icons in extension manager

### ISSUE THREAD

**Issue by NeoBlack** [TYPO3/TYPO3.Icons#269]
The icons for install, deinstall and update an extension in extension manager are too similar.

<img width="129" alt="bladebox_2__typo3_cms_7_6_1-dev_" src="https://cloud.githubusercontent.com/assets/1128085/11143347/a88d546a-89f4-11e5-96c7-b81a7351e91c.png">

Please create icons for install, deinstall and update which are better to differentiate.

**Comment by josefglatz** [comment]
Thought a little bit about. What about changing this to Toggle Switches?

**Comment by benjaminkott** [comment]
we have a set of icons and follow this type of extension to add additional meaning at several places.
If the icon is in context too hard to differentiate we need to add colors, other indicators to the places where the icons are used.
