### ISSUE TITLE
module-workspaces-action-preview-link

### ISSUE THREAD

**Issue by andreaskienast** [TYPO3/TYPO3.Icons#273]
The icon used for generating preview links of a workspace is still a PNG variant.

**Comment by GuessMo** [comment]
![bildschirmfoto 2016-07-26 um 18 28 14](https://cloud.githubusercontent.com/assets/7084139/17146468/ee417d90-535e-11e6-91ca-499eefa186e3.png)

**Comment by GuessMo** [comment]
Icon is no module - renamed it to "actions-version-workspaces-preview-link"
