### ISSUE TITLE
collapse-all icon for category tree

### ISSUE THREAD

**Issue by tmotyl** [TYPO3/TYPO3.Icons#275]
we need a replacement for sysext/t3skin/extjs/images/tree/collapse-all.gif
It is used on category tree toolbar

**Comment by GuessMo** [comment]
![collapse-all](https://cloud.githubusercontent.com/assets/7084139/16914296/342cdf62-4cf1-11e6-8553-49e3bd1318d8.gif)

**Comment by tmotyl** [comment]
thanks
