### ISSUE TITLE
Add icon: Preview page

### ISSUE THREAD

**Issue by dawind** [TYPO3/TYPO3.Icons#278]
In order to be consistent add an icon for page preview.

| record | page |
| --- | --- |
| actions-edit-add | actions-page-new |
| actions-open | actions-page-open |
| actions-view | _missing_ |

**Comment by benjaminkott** [comment]
https://github.com/TYPO3/TYPO3.Icons/blob/master/src/actions/actions-file-view.svg
https://github.com/TYPO3/TYPO3.Icons/blob/master/src/actions/actions-document-view.svg
