### ISSUE TITLE
Replace icon: actions-version-page-open

### ISSUE THREAD

**Issue by dawind** [TYPO3/TYPO3.Icons#279]
As icon actions-page-open is too similar to actions-page-open, replace it.

**Comment by bmack** [comment]
A similar phenomenon is "actions-version-document-remove" which is actually "discard", which is an alias for "delete" (trash), I'd rather have something like  https://typo3.github.io/TYPO3.Icons/icons/actions/actions-delete-restore.html

**Comment by benjaminkott** [comment]
actions-page-open is dropped and now an `alias for actions-file-edit`
