### ISSUE TITLE
Some flag icons miss the viewbox attribute

### ISSUE THREAD

**Issue by georgringer** [TYPO3/TYPO3.Icons#282]
Some of the language flag SVGs have displaying issues in IE11.

The problem appears for example with the French language flag (/typo3/sysext/core/Resources/Public/Icons/Flags/SVG/FR.svg). This happens because of a missing "viewBox" attribute on the "svg" element inside the svg file.
Working flags like the one for German (/typo3/sysext/core/Resources/Public/Icons/Flags/SVG/DE.svg) have this attribute and have no displaying issues.

Stackoverflow answer regarding this issue: http://stackoverflow.com/a/27971837/2987242

The Flags without the "viewBox" attribute also have a different (rectangular) layout in Chrome (see screenshot)

Solution:
Add a "viewBox" attribute on every SVG missing the attribute.

See also https://forge.typo3.org/issues/79595

**Comment by benjaminkott** [comment]
Flags are not part of this repository, I will close the issue here.
