### ISSUE TITLE
Flags should be unified

### ISSUE THREAD

**Issue by andreas-becker** [TYPO3/TYPO3.Icons#283]
The flag icons in the language selection do have different sizes.
It would be great, if all could have the same size.
Maybe switching to https://github.com/lipis/flag-icon-css might fix the problem easily.

**Comment by georgringer** [comment]
could that be related to https://github.com/TYPO3/TYPO3.Icons/issues/282?

**Comment by andreas-becker** [comment]
I don't think it is related, cause the svgs do have different sizes inside the svg-tag.
To understand this problem better, i added a screenshot (Chrome 56 on macOS):
![t3-flags-backend](https://cloud.githubusercontent.com/assets/904496/23202904/7e558b84-f8e0-11e6-85dd-03087ceb451d.png)
As you can see, f.e. the second and the third flag do have different sizes.
It would ne better, if all the flags have the same size.

**Comment by GuessMo** [comment]
the flags are not part of this repository. So please open an issue at https://github.com/behdad/region-flags for unified sizes.

**Comment by benjaminkott** [comment]
As mentioned before, flags are not part of this repository. Will close this issue here.
