### ISSUE TITLE
Some SVGs in typo3 core extension are rendered with unnecessary strings

### ISSUE THREAD

**Issue by erredeco** [TYPO3/TYPO3.Icons#296]
[This issue has been created after the forge issue https://forge.typo3.org/issues/85153]

mimetypes-open-document-formula.svg
mimetypes-media-video-youtube.svg
mimetypes-media-video-vimeo.svg
mimetypes-media-video.svg

those files under "typo3_src-8.7\typo3\sysext\core\Resources\Public\Icons\T3Icons\mimetypes" this folder got some unnecessary styles and defs, which can be safely removed.

This bug is in version 9 as well.

**Comment by benjaminkott** [comment]
cleaned all icons, is solved in current releases - core needs to catch up on usage
