### ISSUE TITLE
actions-chevron-contract missing?

### ISSUE THREAD

**Issue by georgringer** [TYPO3/TYPO3.Icons#308]
Even though https://typo3.github.io/TYPO3.Icons/icons/actions/actions-chevron-contract.html is listed I don't find it in master or 10 LTS?

**Comment by benjaminkott** [comment]
This is a new icon, sadly git has a problem following renames and sometimes makes wrong assumptions. Still looking for a solution to this.

**Comment by benjaminkott** [comment]
will close this one, icon is available in TYPO3 10.4 and forward
