### ISSUE TITLE
Icon for page tsconfig module

### ISSUE THREAD

**Issue by georgringer** [TYPO3/TYPO3.Icons#321]
this is a copy of https://forge.typo3.org/issues/99942 to have a dedicated icon for page tsconfig module

**Comment by benjaminkott** [comment]
see: 
- https://github.com/TYPO3/TYPO3.Icons/blob/main/src/module/module-tsconfig.svg
- https://github.com/TYPO3/TYPO3.Icons/blob/main/src/module/module-template.svg
