### ISSUE TITLE
actions-edit-copy-release

### ISSUE THREAD

**Issue by benjaminkott** [TYPO3/TYPO3.Icons#64]
![edit-copy-release](https://cloud.githubusercontent.com/assets/3243119/10185950/523808e0-674d-11e5-8459-2ac277a0c6d5.png)

**Comment by raphaelokon** [comment]
Ignore the upper reference. I got the issue number wrong. It was actually #65 that should have been referenced. I amended my commit and did a new PR.

**Comment by raphaelokon** [comment]
Picked from list.
