### ISSUE TITLE
actions-input-clear

### ISSUE THREAD

**Issue by benjaminkott** [TYPO3/TYPO3.Icons#71]
![input-clear](https://cloud.githubusercontent.com/assets/3243119/10186187/80b4b98c-674f-11e5-8a74-b237f0f09018.png)

**Comment by raphaelokon** [comment]
Can we use actions-close for this?

**Comment by benjaminkott** [comment]
ja können wir nehmen

**Comment by raphaelokon** [comment]
Cool! Mache ich rein.
